-- SharePay Release 1.0 schema (PostgreSQL). Applied by Flyway in the docker profile.
-- The dev (H2) and test profiles generate the schema from JPA entities instead, so this
-- DDL mirrors those entities and is validated against them (ddl-auto=validate) in Docker.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE workspaces (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)  NOT NULL,
    description VARCHAR(2000),
    created_at  TIMESTAMP     NOT NULL
);

CREATE TABLE workspace_members (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT      NOT NULL REFERENCES workspaces (id),
    user_id      BIGINT      NOT NULL REFERENCES users (id),
    role         VARCHAR(20) NOT NULL,
    created_at   TIMESTAMP   NOT NULL,
    CONSTRAINT uq_workspace_member UNIQUE (workspace_id, user_id)
);

CREATE TABLE events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT      NOT NULL REFERENCES workspaces (id),
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(2000),
    type         VARCHAR(20) NOT NULL,
    currency     VARCHAR(3)  NOT NULL,
    start_date   DATE,
    end_date     DATE,
    status       VARCHAR(20) NOT NULL,
    settled_at   TIMESTAMP,
    created_at   TIMESTAMP   NOT NULL
);

CREATE TABLE event_members (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     BIGINT       NOT NULL REFERENCES events (id),
    display_name VARCHAR(255) NOT NULL,
    email        VARCHAR(255),
    phone        VARCHAR(50),
    user_id      BIGINT REFERENCES users (id),
    created_at   TIMESTAMP    NOT NULL
);

CREATE TABLE categories (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events (id),
    name     VARCHAR(100) NOT NULL
);

CREATE TABLE transactions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id           BIGINT        NOT NULL REFERENCES events (id),
    type               VARCHAR(20)   NOT NULL,
    title              VARCHAR(255)  NOT NULL,
    category_id        BIGINT REFERENCES categories (id),
    amount             NUMERIC(19, 2) NOT NULL,
    tx_date            DATE          NOT NULL,
    description        VARCHAR(2000),
    split_method       VARCHAR(20),
    created_by_user_id BIGINT REFERENCES users (id),
    created_at         TIMESTAMP     NOT NULL
);

CREATE TABLE transaction_payers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id  BIGINT         NOT NULL REFERENCES transactions (id),
    event_member_id BIGINT         NOT NULL REFERENCES event_members (id),
    amount          NUMERIC(19, 2) NOT NULL
);

CREATE TABLE transaction_splits (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id  BIGINT         NOT NULL REFERENCES transactions (id),
    event_member_id BIGINT         NOT NULL REFERENCES event_members (id),
    share_amount    NUMERIC(19, 2) NOT NULL,
    input_value     NUMERIC(19, 4)
);

CREATE TABLE transaction_sponsors (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id  BIGINT         NOT NULL REFERENCES transactions (id),
    event_member_id BIGINT         NOT NULL REFERENCES event_members (id),
    amount          NUMERIC(19, 2) NOT NULL
);

CREATE TABLE receipts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT       NOT NULL REFERENCES transactions (id),
    file_name      VARCHAR(255) NOT NULL,
    content_type   VARCHAR(100) NOT NULL,
    size_bytes     BIGINT       NOT NULL,
    data           BYTEA        NOT NULL,
    created_at     TIMESTAMP    NOT NULL
);

CREATE TABLE ledger_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        BIGINT         NOT NULL REFERENCES events (id),
    event_member_id BIGINT         NOT NULL REFERENCES event_members (id),
    transaction_id  BIGINT REFERENCES transactions (id),
    type            VARCHAR(30)    NOT NULL,
    amount          NUMERIC(19, 2) NOT NULL,
    created_at      TIMESTAMP      NOT NULL
);

CREATE INDEX idx_events_workspace ON events (workspace_id);
CREATE INDEX idx_event_members_event ON event_members (event_id);
CREATE INDEX idx_transactions_event ON transactions (event_id);
CREATE INDEX idx_ledger_event ON ledger_entries (event_id);
CREATE INDEX idx_ledger_member ON ledger_entries (event_member_id);
CREATE INDEX idx_ledger_transaction ON ledger_entries (transaction_id);
